"""Centralized machine-readable error codes for AGENTPAY."""

from enum import StrEnum


class ErrorCode(StrEnum):
    """Machine-readable error code taxonomy for AGENTPAY backend services."""

    INTERNAL_ERROR = "INTERNAL_ERROR"
    INVALID_CONFIGURATION = "INVALID_CONFIGURATION"
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    RESOURCE_CONFLICT = "RESOURCE_CONFLICT"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    DOMAIN_ERROR = "DOMAIN_ERROR"
    APPLICATION_ERROR = "APPLICATION_ERROR"
    INFRASTRUCTURE_ERROR = "INFRASTRUCTURE_ERROR"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
