// AGENTPAY PAGE 012 TRANSACTION OPERATIONS - Production Types
export type TxnTabType = 'REGISTRY' | 'INTENTS' | 'LIFECYCLE' | 'REFUNDS' | 'EVENTS' | 'AUDIT';
export type TxnStatus = 'PENDING' | 'AUTHORIZED' | 'CAPTURED' | 'SETTLED' | 'FAILED' | 'DECLINED' | 'CANCELLED' | 'REFUNDED' | 'PARTIALLY_REFUNDED' | 'DISPUTED' | 'UNDER_REVIEW' | 'BLOCKED';
export type TxnRiskTier = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
export type TxnPaymentMethod = 'VIRTUAL_CARD' | 'CARD' | 'BANK_TRANSFER' | 'ACH' | 'UPI' | 'WALLET' | 'NET_BANKING';
export type TxnRefundStatus = 'REQUESTED' | 'PROCESSING' | 'SUCCEEDED' | 'FAILED' | 'CANCELLED';
export type TxnLifecycleStepStatus = 'COMPLETED' | 'ACTIVE' | 'FAILED' | 'SKIPPED' | 'PENDING';
export type TxnEventType = 'PAYMENT_INTENT.CREATED' | 'AGENT.AUTHENTICATED' | 'CAPABILITY.VERIFIED' | 'POLICY.EVALUATED' | 'RISK.SCORED' | 'AUTHORIZATION.REQUESTED' | 'AUTHORIZATION.APPROVED' | 'AUTHORIZATION.FAILED' | 'PAYMENT.CAPTURED' | 'PAYMENT.FAILED' | 'PROCESSOR.CONFIRMED' | 'WEBHOOK.DELIVERED' | 'WEBHOOK.FAILED' | 'SETTLEMENT.MATCHED' | 'REFUND.REQUESTED' | 'REFUND.COMPLETED' | 'DISPUTE.OPENED';
export type TxnIntentType = 'AUTONOMOUS_CARD_PAYMENT' | 'MERCHANT_PAYOUT_BATCH' | 'VENDOR_INVOICE_CLEARING' | 'SUBSCRIPTION_RENEWAL' | 'REFUND_ISSUANCE';
export type TxnIntentStatus = 'CREATED' | 'REQUIRES_AUTHORIZATION' | 'REQUIRES_ACTION' | 'AUTHORIZED' | 'CAPTURED' | 'PARTIALLY_CAPTURED' | 'FAILED' | 'CANCELLED' | 'REFUNDED' | 'PARTIALLY_REFUNDED' | 'DISPUTED';
export interface TxnRecord { id: string; transactionId: string; paymentIntentId: string; agentId: string; agentName: string; merchant: string; customer: string; requestedAmount: string; authorizedAmount: string; capturedAmount: string; netAmount: string; fees: string; currency: string; paymentMethod: TxnPaymentMethod; paymentMethodDetail: string; processor: string; processorReference: string; status: TxnStatus; riskScore: number; riskTier: TxnRiskTier; policyId: string; policyName: string; policyDecision: 'APPROVED' | 'BLOCKED' | 'HITL_REVIEW' | 'CONDITIONAL'; requiresHumanApproval: boolean; settlementId?: string; settlementBatch?: string; environment: 'PRODUCTION' | 'STAGING' | 'SANDBOX'; region: string; authorizationCode?: string; responseCode: string; attemptCount: number; createdAt: string; updatedAt: string; }
export interface TxnPaymentIntent { id: string; intentId: string; transactionId: string; agentId: string; agentName: string; intentType: TxnIntentType; requestedAmount: string; authorizedAmount: string; capturedAmount: string; currency: string; merchant: string; status: TxnIntentStatus; policyId: string; policyDecision: string; riskScore: number; riskTier: TxnRiskTier; requiresHumanApproval: boolean; humanApprovalStatus?: 'PENDING' | 'APPROVED' | 'REJECTED'; threeDsStatus?: 'AUTHENTICATED' | 'FAILED' | 'NOT_REQUIRED'; processor: string; paymentMethod: TxnPaymentMethod; createdAt: string; updatedAt: string; }
export interface TxnLifecycleStep { stepNumber: number; stepId: string; label: string; description: string; status: TxnLifecycleStepStatus; timestamp?: string; latencyMs?: number; actor: string; detail?: string; }
export interface TxnRefund { id: string; refundId: string; transactionId: string; agentId: string; agentName: string; requestedAmount: string; processedAmount: string; currency: string; reason: string; status: TxnRefundStatus; processor: string; processorReference: string; createdAt: string; completedAt?: string; }
export interface TxnEvent { id: string; eventId: string; transactionId: string; eventType: TxnEventType; timestamp: string; actor: string; latencyMs: number; status: 'DELIVERED' | 'PENDING' | 'FAILED'; responseCode?: number; retryCount: number; auditHash: string; }
export interface TxnAuditEntry { id: string; eventId: string; timestamp: string; actor: string; actorType: 'AGENT' | 'SYSTEM' | 'HUMAN' | 'PROCESSOR'; action: string; decision: string; requestId: string; hash: string; prevHash: string; outcome: 'SUCCESS' | 'FAILURE' | 'BLOCKED' | 'REVIEW'; }
export interface TxnAuthorization { authorizationId: string; transactionId: string; requestedAmount: string; authorizedAmount: string; authorizationCode: string; processor: string; timestamp: string; threeDsStatus: string; avsResult: string; cvvResult: string; policyDecision: string; riskDecision: string; humanApproval?: string; }
export interface TxnCapture { captureId: string; transactionId: string; captureType: 'FULL' | 'PARTIAL'; capturedAmount: string; originalAmount: string; processor: string; status: 'CAPTURED' | 'PARTIALLY_CAPTURED' | 'FAILED'; settlementReference?: string; timestamp: string; }
export interface TxnInspectorDetail extends TxnRecord { authorization?: TxnAuthorization; capture?: TxnCapture; lifecycle: TxnLifecycleStep[]; refunds: TxnRefund[]; events: TxnEvent[]; }
export interface TxnFilterState { searchQuery: string; status: string; processor: string; paymentMethod: string; riskTier: string; agent: string; environment: string; dateRange: string; }
