import {
  ProductionAgentRecord,
  ProductionAgentExecution,
  ProductionAgentPermissionRecord,
  ProductionAgentSecurityRecord,
} from './agent-types';

export const INITIAL_PRODUCTION_AGENTS: ProductionAgentRecord[] = [
  {
    id: 'agt_prod_1',
    agentId: 'AGT-892',
    name: 'Procurement Settlement Agent',
    type: 'AUTONOMOUS',
    owner: 'Finance Operations',
    environment: 'PRODUCTION',
    status: 'ACTIVE',
    riskTier: 'LOW',
    policyBinding: 'AGP-GOV-001 (Micro-Payments)',
    lastActive: '2m ago',
    transactionCount: 1420,
    healthScore: 99.8,
    credentialRotationDays: 18,
  },
  {
    id: 'agt_prod_2',
    agentId: 'AGT-441',
    name: 'Vendor Disbursement Agent',
    type: 'AUTONOMOUS',
    owner: 'Global Treasury Ops',
    environment: 'PRODUCTION',
    status: 'ACTIVE',
    riskTier: 'MEDIUM',
    policyBinding: 'AGP-GOV-004 (Batch Payouts)',
    lastActive: '14m ago',
    transactionCount: 842,
    healthScore: 98.4,
    credentialRotationDays: 5,
  },
  {
    id: 'agt_prod_3',
    agentId: 'AGT-118',
    name: 'Invoice Reconciliation Bot',
    type: 'SUPERVISED',
    owner: 'Accounting Audit',
    environment: 'SANDBOX',
    status: 'SUSPENDED',
    riskTier: 'HIGH',
    policyBinding: 'AGP-GOV-009 (Variance Audit)',
    lastActive: '3h ago',
    transactionCount: 104,
    healthScore: 82.1,
    credentialRotationDays: 0,
  },
];

export const INITIAL_PRODUCTION_EXECUTIONS: ProductionAgentExecution[] = [
  {
    id: 'exec_prod_1',
    executionId: 'EX-99812A',
    agentId: 'AGT-892',
    intent: 'AUTONOMOUS_CARD_PAYMENT',
    action: 'PAYMENT_AUTHORIZE',
    policy: 'AGP-GOV-001',
    riskScore: 12,
    result: 'AUTHORIZED',
    latencyMs: 142,
    timestamp: '08:14:22 UTC',
  },
  {
    id: 'exec_prod_2',
    executionId: 'EX-44109B',
    agentId: 'AGT-441',
    intent: 'MERCHANT_PAYOUT_BATCH',
    action: 'DISBURSEMENT_EXECUTE',
    policy: 'AGP-GOV-004',
    riskScore: 68,
    result: 'REVIEW',
    latencyMs: 380,
    timestamp: '07:55:10 UTC',
  },
];

export const INITIAL_PRODUCTION_PERMISSIONS: ProductionAgentPermissionRecord[] = [
  {
    id: 'perm_prod_1',
    agentId: 'AGT-892',
    resource: 'PAYMENTS',
    capability: 'PAYMENT_AUTHORIZE',
    scope: 'EXECUTE',
    policyRule: 'MAX_LIMIT_$10,000',
    status: 'GRANTED',
  },
  {
    id: 'perm_prod_2',
    agentId: 'AGT-892',
    resource: 'RECONCILIATION',
    capability: 'SETTLEMENT_READ',
    scope: 'READ',
    policyRule: 'ALL_GATEWAYS',
    status: 'GRANTED',
  },
];

export const INITIAL_PRODUCTION_SECURITY: ProductionAgentSecurityRecord[] = [
  {
    id: 'sec_prod_1',
    agentId: 'AGT-892',
    credentialType: 'mTLS Client Cert + API Token',
    mTLSCertificateStatus: 'VALID',
    keyFingerprint: 'SHA256:9981273918237498127391273918',
    lastAuthTimestamp: '08:14:00 UTC',
    auditHash: '0x9981273918237498127391273918',
  },
  {
    id: 'sec_prod_2',
    agentId: 'AGT-118',
    credentialType: 'OAuth2 Client Credentials',
    mTLSCertificateStatus: 'REVOKED',
    keyFingerprint: 'SHA256:1102938102938102938102938102',
    lastAuthTimestamp: '3h ago',
    suspensionReason: 'HIGH_RISK_VARIANCE_POLICY_BREACH',
    auditHash: '0x1102938102938102938102938102',
  },
];
