import {
  SourceTransactionRecord,
  SourcePaymentIntent,
  SourceRefundRecord,
  SourceTransactionEvent,
  SourceTransactionDetail,
  SourcePaymentAttempt,
  LifecycleStep,
} from './source-types';

// ============================================================
// MOCK TRANSACTION REGISTRY — 8 rich records
// ============================================================
export const MOCK_SOURCE_TRANSACTIONS: SourceTransactionRecord[] = [
  {
    id: 'txn_rec_1',
    transactionId: 'TXN-AGP-91F2',
    paymentIntentId: 'PI-99821',
    agentId: 'AGT-892',
    agentName: 'Procurement Automation Agent',
    merchant: 'Acme Hardware Corp',
    customer: 'Enterprise Procurement Pool',
    requestedAmount: '$4,280.00',
    authorizedAmount: '$4,280.00',
    capturedAmount: '$4,280.00',
    currency: 'USD',
    paymentMethod: 'VIRTUAL_CARD',
    paymentMethodDetail: 'VCRD **** 4421 · EXP 08/27',
    processor: 'Stripe Payments US',
    processorReference: 'ch_3P92bY2eZvKYlo2C1Gx7mK4p',
    status: 'SETTLED',
    riskScore: 12,
    riskTier: 'LOW',
    policyBinding: 'AGP-GOV-001',
    policyDecision: 'APPROVED',
    requiresHumanApproval: false,
    settlementId: 'STL-881-A7B',
    environment: 'PRODUCTION',
    region: 'US-EAST-1',
    createdTimestamp: '2026-08-30 08:14:22 UTC',
    updatedTimestamp: '2026-08-30 08:14:23 UTC',
    authorizationCode: 'AUTH-228821',
    responseCode: '00',
    attemptCount: 1,
  },
  {
    id: 'txn_rec_2',
    transactionId: 'TXN-AGP-72D1',
    paymentIntentId: 'PI-77192',
    agentId: 'AGT-441',
    agentName: 'Vendor Payment Agent',
    merchant: 'Global Parts Direct',
    customer: 'Treasury Operations Pool',
    requestedAmount: '$18,420.00',
    authorizedAmount: '$18,420.00',
    capturedAmount: '$0.00',
    currency: 'USD',
    paymentMethod: 'BANK_TRANSFER',
    paymentMethodDetail: 'ACH Transfer · Routing ****4421',
    processor: 'Adyen Global Merchant',
    processorReference: 'D239841KQPXZ1',
    status: 'UNDER_REVIEW',
    riskScore: 68,
    riskTier: 'MEDIUM',
    policyBinding: 'AGP-GOV-004',
    policyDecision: 'HITL_REVIEW',
    requiresHumanApproval: true,
    environment: 'PRODUCTION',
    region: 'EU-WEST-1',
    createdTimestamp: '2026-08-30 07:55:10 UTC',
    updatedTimestamp: '2026-08-30 07:55:15 UTC',
    responseCode: 'R10',
    attemptCount: 2,
  },
  {
    id: 'txn_rec_3',
    transactionId: 'TXN-AGP-11A8',
    paymentIntentId: 'PI-55182',
    agentId: 'AGT-118',
    agentName: 'Invoice Settlement Agent',
    merchant: 'Northstar Logistics Inc',
    customer: 'Northstar Logistics Pool',
    requestedAmount: '$42,800.00',
    authorizedAmount: '$0.00',
    capturedAmount: '$0.00',
    currency: 'USD',
    paymentMethod: 'ACH',
    paymentMethodDetail: 'ACH Debit · Account ****9981',
    processor: 'Visa Direct Network',
    processorReference: 'VD-991827301KL',
    status: 'BLOCKED',
    riskScore: 89,
    riskTier: 'HIGH',
    policyBinding: 'AGP-GOV-009',
    policyDecision: 'BLOCKED',
    requiresHumanApproval: true,
    disputeId: 'DSP-9812-A',
    environment: 'PRODUCTION',
    region: 'US-WEST-2',
    createdTimestamp: '2026-08-29 14:10:00 UTC',
    updatedTimestamp: '2026-08-29 14:10:02 UTC',
    responseCode: 'E51',
    attemptCount: 3,
  },
  {
    id: 'txn_rec_4',
    transactionId: 'TXN-AGP-44C7',
    paymentIntentId: 'PI-33142',
    agentId: 'AGT-290',
    agentName: 'Subscription Renewal Agent',
    merchant: 'CloudStack Enterprise',
    customer: 'Platform Billing Pool',
    requestedAmount: '$9,800.00',
    authorizedAmount: '$9,800.00',
    capturedAmount: '$9,800.00',
    currency: 'USD',
    paymentMethod: 'CARD',
    paymentMethodDetail: 'CARD **** 9812 · VISA',
    processor: 'Stripe Payments US',
    processorReference: 'ch_3Q11bY2eZvKYlo2C',
    status: 'CAPTURED',
    riskScore: 22,
    riskTier: 'LOW',
    policyBinding: 'AGP-GOV-002',
    policyDecision: 'APPROVED',
    requiresHumanApproval: false,
    settlementId: 'STL-772-B3K',
    environment: 'PRODUCTION',
    region: 'US-EAST-1',
    createdTimestamp: '2026-08-30 06:00:01 UTC',
    updatedTimestamp: '2026-08-30 06:00:02 UTC',
    authorizationCode: 'AUTH-992210',
    responseCode: '00',
    attemptCount: 1,
  },
  {
    id: 'txn_rec_5',
    transactionId: 'TXN-AGP-88BB',
    paymentIntentId: 'PI-11920',
    agentId: 'AGT-570',
    agentName: 'Global Vendor Payout Agent',
    merchant: 'SingPost Freight Intl',
    customer: 'Logistics Settlement Pool',
    requestedAmount: '$7,150.00',
    authorizedAmount: '$7,150.00',
    capturedAmount: '$7,150.00',
    currency: 'SGD',
    paymentMethod: 'NET_BANKING',
    paymentMethodDetail: 'DBS Bank · Account ****0021',
    processor: 'Adyen APAC',
    processorReference: 'ADYEN-SGD-8812KP',
    status: 'SETTLED',
    riskScore: 19,
    riskTier: 'LOW',
    policyBinding: 'AGP-GOV-007',
    policyDecision: 'APPROVED',
    requiresHumanApproval: false,
    settlementId: 'STL-991-C1M',
    environment: 'PRODUCTION',
    region: 'AP-SOUTHEAST-1',
    createdTimestamp: '2026-08-30 04:22:10 UTC',
    updatedTimestamp: '2026-08-30 04:22:12 UTC',
    authorizationCode: 'AUTH-117765',
    responseCode: '00',
    attemptCount: 1,
  },
  {
    id: 'txn_rec_6',
    transactionId: 'TXN-AGP-33D2',
    paymentIntentId: 'PI-44812',
    agentId: 'AGT-118',
    agentName: 'Invoice Settlement Agent',
    merchant: 'EastWest Shipping Partners',
    customer: 'EastWest Clearing Account',
    requestedAmount: '$31,000.00',
    authorizedAmount: '$31,000.00',
    capturedAmount: '$0.00',
    currency: 'USD',
    paymentMethod: 'BANK_TRANSFER',
    paymentMethodDetail: 'SWIFT Wire · BIC EASTWEST21',
    processor: 'JPMorgan Chase Payments',
    processorReference: 'JPMCC-31000-X9P',
    status: 'AUTHORIZED',
    riskScore: 44,
    riskTier: 'MEDIUM',
    policyBinding: 'AGP-GOV-004',
    policyDecision: 'APPROVED',
    requiresHumanApproval: false,
    environment: 'PRODUCTION',
    region: 'US-EAST-1',
    createdTimestamp: '2026-08-30 09:41:00 UTC',
    updatedTimestamp: '2026-08-30 09:41:02 UTC',
    authorizationCode: 'AUTH-881129',
    responseCode: '00',
    attemptCount: 1,
  },
  {
    id: 'txn_rec_7',
    transactionId: 'TXN-AGP-51E9',
    paymentIntentId: 'PI-78812',
    agentId: 'AGT-332',
    agentName: 'Refund Issuance Agent',
    merchant: 'Orbital Supplies Corp',
    customer: 'Corporate Card Pool',
    requestedAmount: '$2,100.00',
    authorizedAmount: '$2,100.00',
    capturedAmount: '$2,100.00',
    currency: 'USD',
    paymentMethod: 'VIRTUAL_CARD',
    paymentMethodDetail: 'VCRD **** 8800 · EXP 12/26',
    processor: 'Stripe Payments US',
    processorReference: 'ch_3R77bY2eZvKYlo2C',
    status: 'REFUNDED',
    riskScore: 5,
    riskTier: 'LOW',
    policyBinding: 'AGP-GOV-001',
    policyDecision: 'APPROVED',
    requiresHumanApproval: false,
    environment: 'PRODUCTION',
    region: 'US-EAST-1',
    createdTimestamp: '2026-08-29 16:00:00 UTC',
    updatedTimestamp: '2026-08-29 16:02:11 UTC',
    authorizationCode: 'AUTH-009912',
    responseCode: '00',
    attemptCount: 1,
  },
  {
    id: 'txn_rec_8',
    transactionId: 'TXN-AGP-99FF',
    paymentIntentId: 'PI-99102',
    agentId: 'AGT-891',
    agentName: 'High-Value Procurement Agent',
    merchant: 'Apex Industrial Metals',
    customer: 'Strategic Materials Pool',
    requestedAmount: '$185,000.00',
    authorizedAmount: '$0.00',
    capturedAmount: '$0.00',
    currency: 'USD',
    paymentMethod: 'BANK_TRANSFER',
    paymentMethodDetail: 'SWIFT Wire · BIC APEXMETL01',
    processor: 'Citibank Global Payments',
    processorReference: 'PENDING',
    status: 'REQUIRES_ACTION',
    riskScore: 77,
    riskTier: 'HIGH',
    policyBinding: 'AGP-GOV-012',
    policyDecision: 'HITL_REVIEW',
    requiresHumanApproval: true,
    environment: 'PRODUCTION',
    region: 'US-EAST-1',
    createdTimestamp: '2026-08-30 10:15:00 UTC',
    updatedTimestamp: '2026-08-30 10:15:00 UTC',
    responseCode: 'PENDING',
    attemptCount: 0,
  },
];

// ============================================================
// MOCK PAYMENT INTENTS
// ============================================================
export const MOCK_SOURCE_INTENTS: SourcePaymentIntent[] = [
  {
    id: 'pi_rec_1',
    intentId: 'PI-99821',
    transactionId: 'TXN-AGP-91F2',
    agentId: 'AGT-892',
    agentName: 'Procurement Automation Agent',
    intentType: 'AUTONOMOUS_CARD_PAYMENT',
    requestedAmount: '$4,280.00',
    authorizedAmount: '$4,280.00',
    capturedAmount: '$4,280.00',
    currency: 'USD',
    merchant: 'Acme Hardware Corp',
    customer: 'Enterprise Procurement Pool',
    status: 'CAPTURED',
    policyId: 'AGP-GOV-001',
    policyDecision: 'APPROVED — Micro-Payments Policy',
    riskScore: 12,
    riskTier: 'LOW',
    requiresHumanApproval: false,
    expirationTime: '2026-08-30 09:14:22 UTC',
    createdAt: '2026-08-30 08:14:22 UTC',
    updatedAt: '2026-08-30 08:14:23 UTC',
    processor: 'Stripe Payments US',
    paymentMethod: 'VIRTUAL_CARD',
    threeDsStatus: 'AUTHENTICATED',
  },
  {
    id: 'pi_rec_2',
    intentId: 'PI-77192',
    transactionId: 'TXN-AGP-72D1',
    agentId: 'AGT-441',
    agentName: 'Vendor Payment Agent',
    intentType: 'MERCHANT_PAYOUT_BATCH',
    requestedAmount: '$18,420.00',
    authorizedAmount: '$18,420.00',
    capturedAmount: '$0.00',
    currency: 'USD',
    merchant: 'Global Parts Direct',
    customer: 'Treasury Operations Pool',
    status: 'REQUIRES_AUTHORIZATION',
    policyId: 'AGP-GOV-004',
    policyDecision: 'HITL_REVIEW — Batch Payouts Require Approval',
    riskScore: 68,
    riskTier: 'MEDIUM',
    requiresHumanApproval: true,
    humanApprovalStatus: 'PENDING',
    expirationTime: '2026-08-30 08:55:10 UTC',
    createdAt: '2026-08-30 07:55:10 UTC',
    updatedAt: '2026-08-30 07:55:15 UTC',
    processor: 'Adyen Global Merchant',
    paymentMethod: 'BANK_TRANSFER',
    threeDsStatus: 'NOT_REQUIRED',
  },
  {
    id: 'pi_rec_3',
    intentId: 'PI-55182',
    transactionId: 'TXN-AGP-11A8',
    agentId: 'AGT-118',
    agentName: 'Invoice Settlement Agent',
    intentType: 'VENDOR_INVOICE_CLEARING',
    requestedAmount: '$42,800.00',
    authorizedAmount: '$0.00',
    capturedAmount: '$0.00',
    currency: 'USD',
    merchant: 'Northstar Logistics Inc',
    customer: 'Northstar Logistics Pool',
    status: 'FAILED',
    policyId: 'AGP-GOV-009',
    policyDecision: 'BLOCKED — Variance Audit: Risk Threshold Exceeded',
    riskScore: 89,
    riskTier: 'HIGH',
    requiresHumanApproval: true,
    humanApprovalStatus: 'REJECTED',
    expirationTime: '2026-08-29 15:10:00 UTC',
    createdAt: '2026-08-29 14:10:00 UTC',
    updatedAt: '2026-08-29 14:10:02 UTC',
    processor: 'Visa Direct Network',
    paymentMethod: 'ACH',
    threeDsStatus: 'NOT_REQUIRED',
  },
  {
    id: 'pi_rec_4',
    intentId: 'PI-99102',
    transactionId: 'TXN-AGP-99FF',
    agentId: 'AGT-891',
    agentName: 'High-Value Procurement Agent',
    intentType: 'VENDOR_INVOICE_CLEARING',
    requestedAmount: '$185,000.00',
    authorizedAmount: '$0.00',
    capturedAmount: '$0.00',
    currency: 'USD',
    merchant: 'Apex Industrial Metals',
    customer: 'Strategic Materials Pool',
    status: 'REQUIRES_AUTHORIZATION',
    policyId: 'AGP-GOV-012',
    policyDecision: 'HITL_REVIEW — High-Value Procurement Requires Board Approval',
    riskScore: 77,
    riskTier: 'HIGH',
    requiresHumanApproval: true,
    humanApprovalStatus: 'PENDING',
    expirationTime: '2026-08-30 11:15:00 UTC',
    createdAt: '2026-08-30 10:15:00 UTC',
    updatedAt: '2026-08-30 10:15:00 UTC',
    processor: 'Citibank Global Payments',
    paymentMethod: 'BANK_TRANSFER',
    threeDsStatus: 'NOT_REQUIRED',
  },
];

// ============================================================
// MOCK REFUNDS
// ============================================================
export const MOCK_SOURCE_REFUNDS: SourceRefundRecord[] = [
  {
    id: 'ref_rec_1',
    refundId: 'REF-88219',
    originalTransactionId: 'TXN-AGP-91F2',
    agentId: 'AGT-892',
    agentName: 'Procurement Automation Agent',
    requestedAmount: '$420.00',
    processedAmount: '$420.00',
    currency: 'USD',
    reason: 'CANCELLED_SERVICE',
    reasonDetail: 'Service subscription cancelled by merchant within cooling period.',
    status: 'COMPLETED',
    processor: 'Stripe Payments US',
    processorReference: 're_1892A7b9123XpQR',
    requestedTimestamp: '2026-08-30 09:00:00 UTC',
    completedTimestamp: '2026-08-30 09:01:44 UTC',
    requestedBy: 'SYSTEM_AGENT',
  },
  {
    id: 'ref_rec_2',
    refundId: 'REF-44109',
    originalTransactionId: 'TXN-AGP-51E9',
    agentId: 'AGT-332',
    agentName: 'Refund Issuance Agent',
    requestedAmount: '$2,100.00',
    processedAmount: '$2,100.00',
    currency: 'USD',
    reason: 'DUPLICATE_CHARGE',
    reasonDetail: 'Duplicate payment detected by reconciliation scan.',
    status: 'COMPLETED',
    processor: 'Stripe Payments US',
    processorReference: 're_2109Xm99127QpR1',
    requestedTimestamp: '2026-08-29 16:02:00 UTC',
    completedTimestamp: '2026-08-29 16:04:31 UTC',
    requestedBy: 'RECONCILIATION_ENGINE',
  },
  {
    id: 'ref_rec_3',
    refundId: 'REF-77882',
    originalTransactionId: 'TXN-AGP-72D1',
    agentId: 'AGT-441',
    agentName: 'Vendor Payment Agent',
    requestedAmount: '$5,000.00',
    processedAmount: '$0.00',
    currency: 'USD',
    reason: 'POLICY_VIOLATION',
    reasonDetail: 'Transaction blocked by AGENTGUARD policy — refund initiated.',
    status: 'PROCESSING',
    processor: 'Adyen Global Merchant',
    processorReference: 'PENDING',
    requestedTimestamp: '2026-08-30 07:58:00 UTC',
    requestedBy: 'COMPLIANCE_OFFICER',
  },
];

// ============================================================
// MOCK TRANSACTION EVENTS
// ============================================================
export const MOCK_SOURCE_EVENTS: SourceTransactionEvent[] = [
  {
    id: 'evt_rec_1',
    eventId: 'EVT-TXN-9981',
    transactionId: 'TXN-AGP-91F2',
    eventType: 'PAYMENT_INTENT.CREATED',
    sourceGateway: 'AGENTPAY Core Router',
    timestamp: '2026-08-30 08:14:22.012 UTC',
    latencyMs: 12,
    deliveryStatus: 'DELIVERED',
    retryCount: 0,
    responseStatus: 200,
    auditHash: '0x9981273918237498127391273918',
  },
  {
    id: 'evt_rec_2',
    eventId: 'EVT-TXN-9982',
    transactionId: 'TXN-AGP-91F2',
    eventType: 'POLICY.EVALUATED',
    sourceGateway: 'AGENTGUARD Engine',
    timestamp: '2026-08-30 08:14:22.045 UTC',
    latencyMs: 33,
    deliveryStatus: 'DELIVERED',
    retryCount: 0,
    responseStatus: 200,
    auditHash: '0x44129812739123A8123019827391',
  },
  {
    id: 'evt_rec_3',
    eventId: 'EVT-TXN-9983',
    transactionId: 'TXN-AGP-91F2',
    eventType: 'RISK.SCORED',
    sourceGateway: 'FRAUDGUARD Risk Engine',
    timestamp: '2026-08-30 08:14:22.081 UTC',
    latencyMs: 36,
    deliveryStatus: 'DELIVERED',
    retryCount: 0,
    responseStatus: 200,
    auditHash: '0xB819273FADE123891273912739A1',
  },
  {
    id: 'evt_rec_4',
    eventId: 'EVT-TXN-9984',
    transactionId: 'TXN-AGP-91F2',
    eventType: 'AUTHORIZATION.APPROVED',
    sourceGateway: 'Stripe Payments US',
    timestamp: '2026-08-30 08:14:22.180 UTC',
    latencyMs: 99,
    deliveryStatus: 'DELIVERED',
    retryCount: 0,
    responseStatus: 200,
    auditHash: '0xC98271834120981273918273912C',
  },
  {
    id: 'evt_rec_5',
    eventId: 'EVT-TXN-9985',
    transactionId: 'TXN-AGP-91F2',
    eventType: 'PAYMENT.CAPTURED',
    sourceGateway: 'Stripe Payments US',
    timestamp: '2026-08-30 08:14:22.285 UTC',
    latencyMs: 105,
    deliveryStatus: 'DELIVERED',
    retryCount: 0,
    responseStatus: 200,
    auditHash: '0xD12739182739182C2739182739E1',
  },
  {
    id: 'evt_rec_6',
    eventId: 'EVT-TXN-9986',
    transactionId: 'TXN-AGP-91F2',
    eventType: 'WEBHOOK.DELIVERED',
    sourceGateway: 'AGENTPAY Webhook Engine',
    timestamp: '2026-08-30 08:14:22.390 UTC',
    latencyMs: 105,
    deliveryStatus: 'DELIVERED',
    retryCount: 0,
    responseStatus: 200,
    auditHash: '0xE98271293812739182739182739F',
  },
  {
    id: 'evt_rec_7',
    eventId: 'EVT-TXN-7712',
    transactionId: 'TXN-AGP-72D1',
    eventType: 'PAYMENT_INTENT.CREATED',
    sourceGateway: 'AGENTPAY Core Router',
    timestamp: '2026-08-30 07:55:10.002 UTC',
    latencyMs: 9,
    deliveryStatus: 'DELIVERED',
    retryCount: 0,
    responseStatus: 200,
    auditHash: '0xF00127391827398127391827391F',
  },
  {
    id: 'evt_rec_8',
    eventId: 'EVT-TXN-7713',
    transactionId: 'TXN-AGP-72D1',
    eventType: 'AUTHORIZATION.REQUESTED',
    sourceGateway: 'Adyen Global Merchant',
    timestamp: '2026-08-30 07:55:10.119 UTC',
    latencyMs: 117,
    deliveryStatus: 'FAILED',
    retryCount: 3,
    responseStatus: 503,
    auditHash: '0xA12739182739182739182739183A',
  },
  {
    id: 'evt_rec_9',
    eventId: 'EVT-TXN-1181',
    transactionId: 'TXN-AGP-11A8',
    eventType: 'POLICY.EVALUATED',
    sourceGateway: 'AGENTGUARD Engine',
    timestamp: '2026-08-29 14:10:00.045 UTC',
    latencyMs: 45,
    deliveryStatus: 'DELIVERED',
    retryCount: 0,
    responseStatus: 200,
    auditHash: '0xB99273918273918273918273912B',
  },
  {
    id: 'evt_rec_10',
    eventId: 'EVT-TXN-1182',
    transactionId: 'TXN-AGP-11A8',
    eventType: 'AUTHORIZATION.FAILED',
    sourceGateway: 'Visa Direct Network',
    timestamp: '2026-08-29 14:10:00.210 UTC',
    latencyMs: 165,
    deliveryStatus: 'DELIVERED',
    retryCount: 0,
    responseStatus: 402,
    auditHash: '0xC11273918273918273918273912C',
  },
];

// ============================================================
// MOCK LIFECYCLE — for TXN-AGP-91F2 (SETTLED)
// ============================================================
export const MOCK_LIFECYCLE_SETTLED: LifecycleStep[] = [
  {
    stepNumber: 1,
    stepId: 'INTENT_CREATED',
    label: 'Intent Created',
    description: 'Payment intent created by agent with target merchant and amount',
    status: 'COMPLETED',
    timestamp: '08:14:22.012 UTC',
    latencyMs: 12,
    actor: 'AGT-892 (Procurement Automation Agent)',
    metadata: { intentId: 'PI-99821', amount: '$4,280.00', currency: 'USD' },
  },
  {
    stepNumber: 2,
    stepId: 'IDENTITY_VERIFIED',
    label: 'Identity Verified',
    description: 'Agent identity and credential binding verified by AGENTPAY auth layer',
    status: 'COMPLETED',
    timestamp: '08:14:22.025 UTC',
    latencyMs: 13,
    actor: 'AGENTPAY Auth Engine',
    metadata: { credentialRef: 'CRED-9912', verificationMethod: 'mTLS + API Key' },
  },
  {
    stepNumber: 3,
    stepId: 'CAPABILITY_CHECK',
    label: 'Capability Check',
    description: 'Agent payment capability verified against active policy scope',
    status: 'COMPLETED',
    timestamp: '08:14:22.038 UTC',
    latencyMs: 13,
    actor: 'AGENTGUARD Policy Engine',
    metadata: { allowedLimit: '$10,000.00', requestedAmount: '$4,280.00', verdict: 'WITHIN_SCOPE' },
  },
  {
    stepNumber: 4,
    stepId: 'POLICY_EVALUATED',
    label: 'Policy Evaluated',
    description: 'AGENTGUARD policy AGP-GOV-001 evaluated — transaction approved',
    status: 'COMPLETED',
    timestamp: '08:14:22.045 UTC',
    latencyMs: 7,
    actor: 'AGENTGUARD Engine',
    metadata: { policyId: 'AGP-GOV-001', decision: 'APPROVED', ruleMatched: 'MICRO_PAYMENT_WHITELIST' },
  },
  {
    stepNumber: 5,
    stepId: 'RISK_EVALUATED',
    label: 'Risk Evaluated',
    description: 'FRAUDGUARD risk engine scored transaction — LOW risk, no signals',
    status: 'COMPLETED',
    timestamp: '08:14:22.081 UTC',
    latencyMs: 36,
    actor: 'FRAUDGUARD Risk Engine',
    metadata: { riskScore: '12', riskTier: 'LOW', fraudSignals: 'NONE' },
  },
  {
    stepNumber: 6,
    stepId: 'AUTHORIZATION',
    label: 'Authorization',
    description: 'Payment authorized by Stripe Payments US — code AUTH-228821',
    status: 'COMPLETED',
    timestamp: '08:14:22.180 UTC',
    latencyMs: 99,
    actor: 'Stripe Payments US',
    metadata: { authCode: 'AUTH-228821', responseCode: '00', threeDsStatus: 'AUTHENTICATED' },
  },
  {
    stepNumber: 7,
    stepId: 'CAPTURE',
    label: 'Capture',
    description: 'Full payment captured — $4,280.00 captured successfully',
    status: 'COMPLETED',
    timestamp: '08:14:22.285 UTC',
    latencyMs: 105,
    actor: 'Stripe Payments US',
    metadata: { captureId: 'CAP-228821', captureType: 'FULL', capturedAmount: '$4,280.00' },
  },
  {
    stepNumber: 8,
    stepId: 'PROCESSOR_CONFIRMATION',
    label: 'Processor Confirmation',
    description: 'Processor confirmed transaction receipt and queued for settlement',
    status: 'COMPLETED',
    timestamp: '08:14:22.390 UTC',
    latencyMs: 105,
    actor: 'Stripe Payments US',
    metadata: { processorRef: 'ch_3P92bY2eZvKYlo2C1Gx7mK4p', settlementQueue: 'US-EAST-BATCH-2026-08-30' },
  },
  {
    stepNumber: 9,
    stepId: 'SETTLEMENT',
    label: 'Settlement',
    description: 'Transaction settled and matched to batch STL-881-A7B',
    status: 'COMPLETED',
    timestamp: '08:18:00.000 UTC',
    latencyMs: 221010,
    actor: 'Settlement Engine',
    metadata: { settlementId: 'STL-881-A7B', batchId: 'BATCH-2026-08-30-001', netAmount: '$4,224.15' },
  },
  {
    stepNumber: 10,
    stepId: 'AUDIT',
    label: 'Audit Logged',
    description: 'Complete transaction audit trail logged and hash verified',
    status: 'COMPLETED',
    timestamp: '08:18:00.055 UTC',
    latencyMs: 55,
    actor: 'AGENTPAY Audit Engine',
    metadata: { auditHash: '0xD12739182739182C2739182739E1', recordId: 'AUD-91F2-FINAL' },
  },
];

// ============================================================
// MOCK LIFECYCLE — for TXN-AGP-11A8 (BLOCKED)
// ============================================================
export const MOCK_LIFECYCLE_BLOCKED: LifecycleStep[] = [
  {
    stepNumber: 1,
    stepId: 'INTENT_CREATED',
    label: 'Intent Created',
    description: 'Payment intent created by Invoice Settlement Agent',
    status: 'COMPLETED',
    timestamp: '14:10:00.002 UTC',
    latencyMs: 9,
    actor: 'AGT-118 (Invoice Settlement Agent)',
    metadata: { intentId: 'PI-55182', amount: '$42,800.00', currency: 'USD' },
  },
  {
    stepNumber: 2,
    stepId: 'IDENTITY_VERIFIED',
    label: 'Identity Verified',
    description: 'Agent identity verified',
    status: 'COMPLETED',
    timestamp: '14:10:00.015 UTC',
    latencyMs: 13,
    actor: 'AGENTPAY Auth Engine',
    metadata: {},
  },
  {
    stepNumber: 3,
    stepId: 'CAPABILITY_CHECK',
    label: 'Capability Check',
    description: 'Amount exceeds agent-scoped daily limit — escalated to policy review',
    status: 'COMPLETED',
    timestamp: '14:10:00.030 UTC',
    latencyMs: 15,
    actor: 'AGENTGUARD Policy Engine',
    metadata: { allowedLimit: '$25,000.00', requestedAmount: '$42,800.00', verdict: 'LIMIT_EXCEEDED' },
  },
  {
    stepNumber: 4,
    stepId: 'POLICY_EVALUATED',
    label: 'Policy Evaluated',
    description: 'AGENTGUARD policy AGP-GOV-009 blocked transaction — variance audit triggered',
    status: 'FAILED',
    timestamp: '14:10:00.045 UTC',
    latencyMs: 15,
    actor: 'AGENTGUARD Engine',
    metadata: { policyId: 'AGP-GOV-009', decision: 'BLOCKED', ruleMatched: 'VARIANCE_AUDIT_TRIGGER' },
  },
  {
    stepNumber: 5,
    stepId: 'RISK_EVALUATED',
    label: 'Risk Evaluated',
    description: 'HIGH risk detected — velocity and geo-risk flags triggered',
    status: 'FAILED',
    timestamp: '14:10:00.081 UTC',
    latencyMs: 36,
    actor: 'FRAUDGUARD Risk Engine',
    metadata: { riskScore: '89', riskTier: 'HIGH', fraudSignals: 'VELOCITY_FLAG, GEO_RISK' },
  },
  {
    stepNumber: 6,
    stepId: 'AUTHORIZATION',
    label: 'Authorization',
    description: 'Authorization not attempted — transaction blocked by policy',
    status: 'SKIPPED',
    actor: 'N/A',
    metadata: {},
  },
  {
    stepNumber: 7,
    stepId: 'CAPTURE',
    label: 'Capture',
    description: 'Capture not attempted',
    status: 'SKIPPED',
    actor: 'N/A',
    metadata: {},
  },
  {
    stepNumber: 8,
    stepId: 'PROCESSOR_CONFIRMATION',
    label: 'Processor Confirmation',
    description: 'Not reached',
    status: 'SKIPPED',
    actor: 'N/A',
    metadata: {},
  },
  {
    stepNumber: 9,
    stepId: 'SETTLEMENT',
    label: 'Settlement',
    description: 'Not reached',
    status: 'SKIPPED',
    actor: 'N/A',
    metadata: {},
  },
  {
    stepNumber: 10,
    stepId: 'AUDIT',
    label: 'Audit Logged',
    description: 'Block event audit trail logged',
    status: 'COMPLETED',
    timestamp: '14:10:00.210 UTC',
    latencyMs: 10,
    actor: 'AGENTPAY Audit Engine',
    metadata: { auditHash: '0xC11273918273918273918273912C', recordId: 'AUD-11A8-BLOCKED' },
  },
];

// ============================================================
// MOCK FULL TRANSACTION DETAIL — TXN-AGP-91F2
// ============================================================
export const MOCK_TXN_DETAIL_91F2: SourceTransactionDetail = {
  ...MOCK_SOURCE_TRANSACTIONS[0],
  authorization: {
    authorizationId: 'AUTH-228821',
    transactionId: 'TXN-AGP-91F2',
    requestedAmount: '$4,280.00',
    authorizedAmount: '$4,280.00',
    authorizationCode: 'AUTH-228821',
    processor: 'Stripe Payments US',
    timestamp: '2026-08-30 08:14:22.180 UTC',
    threeDsStatus: 'AUTHENTICATED',
    avsResult: 'MATCH',
    cvvResult: 'MATCH',
    policyDecision: 'AGP-GOV-001 APPROVED',
    riskDecision: 'LOW RISK — Score 12',
    humanApproval: 'NOT_REQUIRED',
  },
  capture: {
    captureId: 'CAP-228821',
    transactionId: 'TXN-AGP-91F2',
    captureType: 'FULL',
    capturedAmount: '$4,280.00',
    originalAmount: '$4,280.00',
    processor: 'Stripe Payments US',
    status: 'CAPTURED',
    settlementReference: 'STL-881-A7B',
    timestamp: '2026-08-30 08:14:22.285 UTC',
  },
  attempts: [
    {
      id: 'att_1',
      attemptId: 'ATT-91F2-001',
      transactionId: 'TXN-AGP-91F2',
      attemptNumber: 1,
      processor: 'Stripe Payments US',
      connector: 'CARD',
      route: 'US-EAST-1',
      requestedAmount: '$4,280.00',
      status: 'CAPTURED',
      responseCode: '00',
      responseMessage: 'APPROVED',
      latencyMs: 180,
      processorFee: '$55.85',
      processorReference: 'ch_3P92bY2eZvKYlo2C1Gx7mK4p',
      timestamp: '2026-08-30 08:14:22.000 UTC',
    },
  ],
  events: MOCK_SOURCE_EVENTS.filter(e => e.transactionId === 'TXN-AGP-91F2'),
  risk: {
    transactionId: 'TXN-AGP-91F2',
    riskScore: 12,
    riskTier: 'LOW',
    velocityFlag: false,
    geoRiskFlag: false,
    deviceRiskFlag: false,
    agentRiskFlag: false,
    fraudSignals: [],
    policyViolations: [],
    evaluatedAt: '2026-08-30 08:14:22.081 UTC',
    evaluatedBy: 'FRAUDGUARD Risk Engine v2.4',
  },
  policy: {
    transactionId: 'TXN-AGP-91F2',
    policyId: 'AGP-GOV-001',
    policyName: 'Micro-Payments Autonomous Policy',
    decision: 'APPROVED',
    spendLimit: '$10,000.00',
    appliedRule: 'MICRO_PAYMENT_WHITELIST',
    approvalRequired: false,
    evaluatedAt: '2026-08-30 08:14:22.045 UTC',
    decisionReason: 'Transaction within approved merchant category and amount limit.',
  },
  metadata: [
    { key: 'order_id', value: 'ORD-ACME-2891', source: 'MERCHANT_API', createdAt: '2026-08-30 08:14:22 UTC' },
    { key: 'agent_intent', value: 'HARDWARE_PROCUREMENT', source: 'AGENT_CONTEXT', createdAt: '2026-08-30 08:14:22 UTC' },
    { key: 'environment', value: 'PRODUCTION', source: 'AGENTPAY_CORE', createdAt: '2026-08-30 08:14:22 UTC' },
    { key: 'region', value: 'US-EAST-1', source: 'AGENTPAY_CORE', createdAt: '2026-08-30 08:14:22 UTC' },
    { key: 'campaign_ref', value: 'PROC-Q3-2026', source: 'ENTERPRISE_PLATFORM', createdAt: '2026-08-30 08:14:22 UTC' },
  ],
  participants: [
    { role: 'AGENT', id: 'AGT-892', name: 'Procurement Automation Agent', region: 'US-EAST-1', accountRef: 'ACC-89200' },
    { role: 'MERCHANT', id: 'MER-11002', name: 'Acme Hardware Corp', region: 'US-EAST-1', accountRef: 'ACC-11002' },
    { role: 'CUSTOMER', id: 'POOL-9910', name: 'Enterprise Procurement Pool', region: 'US-EAST-1', accountRef: 'ACC-99100' },
    { role: 'PROCESSOR', id: 'PROC-STRIPE', name: 'Stripe Payments US', region: 'US-EAST-1' },
  ],
  lifecycle: MOCK_LIFECYCLE_SETTLED,
  refunds: MOCK_SOURCE_REFUNDS.filter(r => r.originalTransactionId === 'TXN-AGP-91F2'),
};

// ============================================================
// MOCK PAYMENT ATTEMPTS — for display in attempts tab
// ============================================================
export const MOCK_ALL_ATTEMPTS: SourcePaymentAttempt[] = [
  {
    id: 'att_1',
    attemptId: 'ATT-91F2-001',
    transactionId: 'TXN-AGP-91F2',
    attemptNumber: 1,
    processor: 'Stripe Payments US',
    connector: 'CARD',
    route: 'US-EAST-1',
    requestedAmount: '$4,280.00',
    status: 'CAPTURED',
    responseCode: '00',
    responseMessage: 'APPROVED',
    latencyMs: 180,
    processorFee: '$55.85',
    processorReference: 'ch_3P92bY2eZvKYlo2C1Gx7mK4p',
    timestamp: '2026-08-30 08:14:22.000 UTC',
  },
  {
    id: 'att_2',
    attemptId: 'ATT-72D1-001',
    transactionId: 'TXN-AGP-72D1',
    attemptNumber: 1,
    processor: 'Adyen Global Merchant',
    connector: 'BANK_TRANSFER',
    route: 'EU-WEST-1',
    requestedAmount: '$18,420.00',
    status: 'FAILED',
    responseCode: 'E05',
    responseMessage: 'INSUFFICIENT_FUNDS',
    latencyMs: 220,
    processorFee: '$0.00',
    processorReference: 'D239841KQPXZ1-01',
    timestamp: '2026-08-30 07:55:10.119 UTC',
    errorCode: 'ADYEN_E05',
    errorMessage: 'Insufficient funds in source account.',
  },
  {
    id: 'att_3',
    attemptId: 'ATT-72D1-002',
    transactionId: 'TXN-AGP-72D1',
    attemptNumber: 2,
    processor: 'Adyen Global Merchant',
    connector: 'BANK_TRANSFER',
    route: 'EU-WEST-1',
    requestedAmount: '$18,420.00',
    status: 'UNDER_REVIEW',
    responseCode: 'R10',
    responseMessage: 'PENDING_REVIEW',
    latencyMs: 117,
    processorFee: '$0.00',
    processorReference: 'D239841KQPXZ1',
    timestamp: '2026-08-30 07:55:20.890 UTC',
  },
  {
    id: 'att_4',
    attemptId: 'ATT-11A8-001',
    transactionId: 'TXN-AGP-11A8',
    attemptNumber: 1,
    processor: 'Visa Direct Network',
    connector: 'ACH',
    route: 'US-WEST-2',
    requestedAmount: '$42,800.00',
    status: 'FAILED',
    responseCode: 'E51',
    responseMessage: 'BLOCKED_BY_POLICY',
    latencyMs: 45,
    processorFee: '$0.00',
    processorReference: 'VD-991827301KL-01',
    timestamp: '2026-08-29 14:10:00.165 UTC',
    errorCode: 'AGENTGUARD_BLOCK_009',
    errorMessage: 'Transaction blocked by AGENTGUARD policy AGP-GOV-009.',
  },
];
